
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ME
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private ArrayList<questions> listeQuestions;
private int indexQuestionCourante = 0;
private int score = 0;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
public FenetreQuiz() {
    initComponents(); 

    listeQuestions = new ArrayList<>();


    listeQuestions.add(new questions(
            "Quelle est la capitale de la France ?",
            "Paris", "Londres", "Berlin", "Madrid",
            1));

    listeQuestions.add(new questions(
            "Combien font 5 × 6 ?",
            "30", "35", "25", "28",
            1));

    listeQuestions.add(new questions(
            "Quel océan borde l’Europe ?",
            "Arctic", "Pacifique", "Indien", "Atlantique",
            4));

    listeQuestions.add(new questions(
            "La Terre est...",
            "Plate", "Ronde", "Un triangle", "Un cube",
            2));

    listeQuestions.add(new questions(
            "Quel langage utilise NetBeans ?",
            "Python", "java", "C++", "HTML",
            2));

    afficherQuestionCourante();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnrep1 = new javax.swing.JButton();
        btnrep2 = new javax.swing.JButton();
        btnrep3 = new javax.swing.JButton();
        btnrep4 = new javax.swing.JButton();
        FeedbackText = new javax.swing.JLabel();
        btnQsuiv = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("Question 1");

        btnrep1.setText("Réponse 1");
        btnrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrep1ActionPerformed(evt);
            }
        });

        btnrep2.setText("Réponse 2");
        btnrep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrep2ActionPerformed(evt);
            }
        });

        btnrep3.setText("Réponse 3");
        btnrep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrep3ActionPerformed(evt);
            }
        });

        btnrep4.setText("Réponse 4");
        btnrep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrep4ActionPerformed(evt);
            }
        });

        FeedbackText.setText("Message Feedback");

        btnQsuiv.setText("Question Suivante ->");
        btnQsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQsuivActionPerformed(evt);
            }
        });

        lblScore.setText("Score : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblQuestion)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQsuiv)
                        .addGap(142, 142, 142))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnrep1)
                        .addGap(18, 18, 18)
                        .addComponent(btnrep2)
                        .addGap(18, 18, 18)
                        .addComponent(btnrep3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnrep4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(FeedbackText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(lblScore)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblQuestion)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrep3)
                    .addComponent(btnrep2)
                    .addComponent(btnrep4)
                    .addComponent(btnrep1))
                .addGap(27, 27, 27)
                .addComponent(FeedbackText)
                .addGap(18, 18, 18)
                .addComponent(btnQsuiv)
                .addGap(18, 18, 18)
                .addComponent(lblScore)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrep2ActionPerformed
        // TODO add your handling code here:
        verifierReponse(2);
    }//GEN-LAST:event_btnrep2ActionPerformed

    private void btnrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrep1ActionPerformed
        // TODO add your handling code here:  
        verifierReponse(1);
    }//GEN-LAST:event_btnrep1ActionPerformed

    private void btnrep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrep3ActionPerformed
        // TODO add your handling code here:
        verifierReponse(2);
    }//GEN-LAST:event_btnrep3ActionPerformed

    private void btnrep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrep4ActionPerformed
        // TODO add your handling code here:
        verifierReponse(4);
    }//GEN-LAST:event_btnrep4ActionPerformed

    private void btnQsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQsuivActionPerformed
        // TODO add your handling code here:
    indexQuestionCourante++;

  
    if (indexQuestionCourante < listeQuestions.size()) {

        afficherQuestionCourante();

    } else {

        FeedbackText.setText("Quiz terminé ! Score final : " + score 
                             + " / " + listeQuestions.size());

    
        btnQsuiv.setEnabled(false);

      
        btnrep1.setEnabled(false);
        btnrep2.setEnabled(false);
        btnrep3.setEnabled(false);
        btnrep4.setEnabled(false);
    }


        
    
    }//GEN-LAST:event_btnQsuivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FeedbackText;
    private javax.swing.JButton btnQsuiv;
    private javax.swing.JButton btnrep1;
    private javax.swing.JButton btnrep2;
    private javax.swing.JButton btnrep3;
    private javax.swing.JButton btnrep4;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

private void afficherQuestionCourante() {
    btnQsuiv.setEnabled(false);
    questions q = listeQuestions.get(indexQuestionCourante);

    
    lblQuestion.setText(q.getIntitule());

    
    btnrep1.setText(q.getProposition1());
    btnrep2.setText(q.getProposition2());
    btnrep3.setText(q.getProposition3());
    btnrep4.setText(q.getProposition4());

    
    btnrep1.setEnabled(true);
    btnrep2.setEnabled(true);
    btnrep3.setEnabled(true);
    btnrep4.setEnabled(true);

    FeedbackText.setText("");  
}
//////////////////////// VERIFIER REPONSE ///////////////////////////////
private void verifierReponse(int choixUtilisateur) {

    questions q = listeQuestions.get(indexQuestionCourante);

    
    if (choixUtilisateur == q.getIndexBonneReponse()) {
        FeedbackText.setText("Bonne réponse !");
        score++;
        lblScore.setText("Score : " + score);

    } else {
        FeedbackText.setText("Mauvaise réponse !");
    }

    btnrep1.setEnabled(false);
    btnrep2.setEnabled(false);
    btnrep3.setEnabled(false);
    btnrep4.setEnabled(false);
    btnQsuiv.setEnabled(true);
}

}
